### ISSUE TITLE
Why didn't you use the fork button?

### ISSUE THREAD

**Issue by andres-asm** [m4xw/RetroArch_LibNX#2]
There is no original repo so we can't diff easily with upstream.

**Comment by m4xw** [comment]
Because I don't work on Github, and this is only a mirror-repository.

Any upstream switch changes won't work anyway, because upstream uses libtransistor.

Non the less you can always add a 2nd origin.

Can I close this?

**Comment by m4xw** [comment]
Anyway you can always just diff from dd0ad288184f54ca933fc79185fe098aa571eeb9 which is the last original commit.

My develop and master branches will be squashed and cleaned up later down the road anyway, not gonna stay dirty like this

Keep that in mind if you plan on getting changes upstream, I would wait 1.0 and the cleanup

Edit: https://git.m4xw.net/Switch/RetroArch/RetroArch/compare/dd0ad288184f54ca933fc79185fe098aa571eeb9...develop?w=1
Edit2: https://git.m4xw.net/Switch/RetroArch (all sources)
