### ISSUE TITLE
Upstreaming changes

### ISSUE THREAD

**Issue by hizzlekizzle** [m4xw/RetroArch_LibNX#3]
Hi there, we (upstream RetroArch team) just heard about your work through your thread on GBATemp and would be interested in upstreaming your changes at some point. I haven't had a chance to go through all of your commits, but just skimming through it looks like everything is nice and compartmentalized, so that should make merging the changes relatively easy.

Do you guys have any thoughts/preferences on how best to proceed?

**Comment by m4xw** [comment]
Hey!
First thanks for contacting me, I actually hoped to get the changes upstream sooner or later.
Right now I pretty much replace libtransistor, but my goal would be co-existing besides libtransistor.
I tried not to make any breaking changed with #ifdef's for libtransistor, but you know how it is, there's always *something*.

Anyway, develop is somewhat stable and *could* be merged, but my feature branches are nearly finished, but still unstable.

I would like to fix that, after that squash everything up and go!

Btw is there a way to contact your team outside of github?

It would  be great for me if I have someone to talk to for retroarch specific questions.

Often I am not sure if its switch quirks, just some retroarch bugs or my code (not having a debugger doesn't help either :D )

Btw, one of your team already asked why I didn't use the fork button (i work with gitlab), if it does help your team in any way I can just recreate the repo (fork) and mirror my changes up.

There isn't really any collab going on, all the code is basically just me (besides core ports)

Anyway if you have any questions, feel free to ask.

**Comment by hizzlekizzle** [comment]
No big hurry. If you have features that are almost finished, waiting for them and then squash-and-go sounds good to me :)

Having it forked here helps when it comes time to merge, since github has a nice interface for that, but it's no big deal either way.

You can contact us at #retroarch on Freenode IRC or discord (https://discord.gg/C4amCeV). Most of the activity is on discord these days, so you'll get the most rapid response there. If you're more comfortable with IRC, just ping me (I'm 'hunterk' on both) and I'll see it pretty soon and can get some other folks' attention.

**Comment by m4xw** [comment]
Thank you very much. I actually prefer IRC, so I guess I will join both :>
